### ISSUE TITLE
Nowy dialog Elementy/Jednostki

### ISSUE THREAD

**Issue by mrgleba** [Weles3Doc/W3Doc#10]
Robimy osobnego gifa na:
 - wywołanie okna z menu (jak się zmieni interface strony to będzie trzeba tylko to poprawić)
 - operacje w każdej z zakładek

**Comment by gzeadmpl** [comment]
Zrobione. Spr plz @mrgleba
https://doc.weles3.pl/administracyjne/stawki/Dodanie-jednostki-do-systemu.html
