### ISSUE TITLE
Nowy dialog Elementy/Grupy liczników

### ISSUE THREAD

**Issue by mrgleba** [Weles3Doc/W3Doc#11]
Robimy osobnego gifa na:
 - wywołanie okna z menu (jak się zmieni interface strony to będzie trzeba tylko to poprawić)
 - operacje w każdej z zakładek

**Comment by gzeadmpl** [comment]
Zrobione. Michał, spr plz @mrgleba
https://doc.weles3.pl/administracyjne/liczniki/Dodanie-grupy-licznikow-do-systemu.html

**Comment by mrgleba** [comment]
Super
