### ISSUE TITLE
Dokumentacja nowego okna Funkcje/Administratorzy

### ISSUE THREAD

**Issue by mrgleba** [Weles3Doc/W3Doc#3]
Robimy osobnego gifa na:
 - wywołanie okna z menu (jak się zmieni interface strony to będzie trzeba tylko to poprawić)
 - operacje w każdej z zakładek

**Comment by pseadmpl** [comment]
@mrgleba doku uaktualniona
https://doc.weles3.pl/ogolne/uzytkownicyiuprawnienia/Dodawanie-nowego-uzytkownika.html
spr plz
