### ISSUE TITLE
Nowe okno Zasoby/Kontrahenci

### ISSUE THREAD

**Issue by mrgleba** [Weles3Doc/W3Doc#5]
Robimy osobnego gifa na:
 - wywołanie okna z menu (jak się zmieni interface strony to będzie trzeba tylko to poprawić)
 - operacje w każdej z zakładek

**Comment by pseadmpl** [comment]
Michał - sprawdź instrukcję
https://doc.weles3.pl/ksiegowe/system/Edycja-kontrahentow.html
poprawiona

jest w porządku ?
