### ISSUE TITLE
Nowe okno FUnkcje/Ochrona danych osobowych

### ISSUE THREAD

**Issue by mrgleba** [Weles3Doc/W3Doc#7]
Robimy osobnego gifa na:
 - wywołanie okna z menu (jak się zmieni interface strony to będzie trzeba tylko to poprawić)
 - operacje w każdej z zakładek

**Comment by pseadmpl** [comment]
Instrukcja poprawiona:
https://doc.weles3.pl/ogolne/system/Zgody-RODO.html
spr plz

**Comment by pseadmpl** [comment]
@mrgleba
